os: linux
language: go
go:
- 1.16.3  # Bazel still uses its own version
env:
  global:
  - BAZEL_VERSION=4.0.0
  - BAZEL_SHA256=bd7a3a583a18640f58308c26e654239d412adaa833b6b6a7b57a216ab62fabc2
before_install:
- |
  wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
  echo "${BAZEL_SHA256}  install.sh" | sha256sum -c
  chmod +x install.sh
install:
- |
  ./install.sh --user
  rm -f install.sh
script:
- travis_wait bazel build --config=ci //...
- bazel test --config=ci //...
- go build
- go test
